apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: springapp
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spring
spec:
  hosts:
  - "test.com"
  gateways:
  - springapp
  http:
  - match:
    - uri:
        exact: /local
    - uri:
        prefix: /ipc
    route:
    - destination:
        host: service1
        port:
          number: 80
