apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rvt-test
  namespace: default
spec:
  dnsNames:
    - rvt.test.com
  secretName: rvt-test-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
