
kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  type: NodePort
  ports:
    - nodePort: 30161
      port: 80
      targetPort: 9092

#kind: Service
#apiVersion: v1
#metadata:
#  name: account-service
#spec:
#  selector:
#    app: account-service
#  type: ClusterIP
#  ports:
#      port: 80
#      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: felipemeriga1/account-service:latest
          ports:
            - containerPort: 9092
