apiVersion: v1
kind: Service
metadata:
  name: ambassador-app
  labels:
    app: ambassador-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30002
  selector:
    app: ambassador-app

