apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: ".1"
        volumeMounts:
             - mountPath: "/usr/share/nginx/html"
               name: task-pv-claim
      imagePullSecrets: 
          - name: harbor
      setHostnameAsFQDN: true
      volumes:
      - name: task-pv-claim
        persistentVolumeClaim: 
                  claimName: task-pv-claim

