apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: appport
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  type: NodePort
status:
  loadBalancer: {}
