apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: ingress-nginx
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
