apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: busybox
        ports:
        - containerPort: 80



apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: helloworld
    app:
  type: NodePort
  ports:
  - port: 80
    target: 80
    NodePort: 30080
